### PR TITLE
Fix dereference behavior on mixed subscript and arrow / dot operators

### LINKED ISSUE #164: On-heap struct pointer assignment corrupts memory
Considering the following example minimum arena implementation:

```c
#include <stdlib.h>

typedef enum {
    A,
    B
} type_t;

typedef struct {
    type_t typ;
} data_t;

typedef struct {
    int cap;
    int size;
    data_t *data;
} arena_t;

arena_t *arena_init(int cap) {
    arena_t *arena = malloc(sizeof(arena_t));
    arena->cap = cap;
    arena->size = 0;
    arena->data = calloc(cap, sizeof(data_t));
    return arena;
}

data_t *arena_alloc(arena_t *arena) {
    if (arena->size + 1 >= arena->cap)
        return NULL;

    return &arena->data[arena->size++];
}

void arena_free(arena_t *arena) {
    free(arena->data);
    free(arena);
}

int main() {
    arena_t *arena = arena_init(1024);
    data_t *data = arena_alloc(arena);
    printf("%d\n", arena->data);
    data->typ = B;
    printf("%d\n", arena->data);
    arena_free(arena);

    return 0;
}
```

I expect that it would output 2 numbers that refers to same memory address where `arena->data` resides, however, using shecc results in the second number is different to the first one, and same as the integer value of enum `B` previously assigned.

Using gcc to compile this program would have expected result however.

### LINKED ISSUE #165: Invalid char pointer deference behavior
Considering the following code:
```c
#include <stdlib.h>
#include <string.h>

char a[100];

typedef struct {
    char *raw;
} data_t;

void init_data(data_t *data, char *raw) {
    data->raw = raw;
}

int main() {
    strcpy(a, "DATA");
    data_t *data = malloc(sizeof(data_t));
    init_data(data, a);
    
    char *raw = data->raw;
    printf("%c\n", a[0]);
    printf("%c\n", raw[0]);
    printf("%c\n", data->raw[0]);
    
    
    free(data);

    return 0;
}
```

Using gcc to compile the program and run it, it would output:
```
D
D
D
```

But using shecc, it would output:
```
D
D
�
```

This happens because of the incorrect deference assembly code.

### LINKED ISSUE #181: Incorrect double free behavior
Using the code below to initialize buckets for hashmap and frees hashmap:

```c
#include <stdlib.h>

typedef struct hashmap_node {
    char *key;
    void *val;
    struct hashmap_node *next;
} hashmap_node_t;

typedef struct {
    int size;
    hashmap_node_t **buckets;
} hashmap_t;

hashmap_t *hashmap_create(int size)
{
    hashmap_t *map = malloc(sizeof(hashmap_t));
    map->size = size;
    map->buckets = malloc(size * sizeof(hashmap_node_t *));

    for (int i = 0; i < map->size; i++)
        map->buckets[i] = 0;

    return map;
}

void hashmap_free(hashmap_t *map)
{
    for (int i = 0; i < map->size; i++) {
        for (hashmap_node_t *cur = map->buckets[i], *next; cur; cur = next) {
            next = cur->next;
            free(cur->key);
            free(cur->val);
            free(cur);
            cur = next;
        }
    }

    free(map->buckets);
    free(map);
}

int main()
{
    hashmap_t *map = hashmap_create(16);
    map->buckets[0] = malloc(sizeof(hashmap_node_t)); // Simulates put at first bucket
    map->buckets[0]->key = calloc(1, sizeof(char));
    map->buckets[0]->val = malloc(sizeof(int));
    map->buckets[0]->next = NULL;
    hashmap_free(map);
    return 0;
}
```

Compile with gcc will exit normally, while compile with shecc will cause double free, which is abnormal.

### PR DESCRIPTION
**Pull request by ChAoSUnItY**
- Fix #165.
- Fix #181, as it's already introduced into upstream source code by #179.
- Fix #164.
- This change could hopefully allow us to safely operate more dynamic data strctures without having troubles. 
 <div id='description'>
<h3>Summary by Bito</h3>
This pull request fixes a double free error in the globals file and enhances type safety in the parser by changing variable types from int to bool. It also introduces new tests for dynamic data structures, improving the robustness of the codebase and addressing issues #165, #181, and #164.
<br>
<br>
<b>Unit tests added</b>: True
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>

### CODE REVIEW

File: tests/driver.sh [hunk 1]
```diff
@@ -433,6 +433,38 @@ int main() {
 }
 EOF
 
+# Mixed subscription and arrow operator,
```
Comment (DrXiao) [inline tests/driver.sh:436]: I recommend rewrite it as `Mixed subscript and arrow operators`
(In C99 6.5.2.1, `[ ]` is called  the "subscript operator".)

File: src/parser.c [hunk 2]
```diff
@@ -1260,6 +1260,18 @@ void read_lvalue(lvalue_t *lvalue,
     while (lex_peek(T_open_square, NULL) || lex_peek(T_arrow, NULL) ||
            lex_peek(T_dot, NULL)) {
         if (lex_accept(T_open_square)) {
+            if (lvalue->is_reference && lvalue->is_ptr && is_member) {
```
Comment (DrXiao) [inline src/parser.c:1263]: How about writing some comments here?

File: src/parser.c [hunk 3]
```diff
@@ -1260,6 +1260,20 @@ void read_lvalue(lvalue_t *lvalue,
     while (lex_peek(T_open_square, NULL) || lex_peek(T_arrow, NULL) ||
            lex_peek(T_dot, NULL)) {
         if (lex_accept(T_open_square)) {
+            /* if previous operator requires deference, deference here, then
```
Comment (jserv) [inline src/parser.c:1263]: Should be "dereference."

File: src/parser.c [hunk 4]
```diff
@@ -1260,6 +1260,20 @@ void read_lvalue(lvalue_t *lvalue,
...
+             * offset later */
```
Comment (jserv) [inline src/parser.c:1264]: Improve the descriptions.

Comment (ChAoSUnItY) [reply src/parser.c:1264]: I just tested additional expressions e.g. "data.raw[0]" to better conclude this patch's effect, apperently this does also fix deference behavior on mixed subscript and dot operator (which also produced incorrect code before).

**Review by jserv — CHANGES_REQUESTED** [review]
Clarify the use of "deference" and "dereference" in the wording.

File: src/parser.c [hunk 5]
```diff
@@ -1260,6 +1260,22 @@ void read_lvalue(lvalue_t *lvalue,
     while (lex_peek(T_open_square, NULL) || lex_peek(T_arrow, NULL) ||
            lex_peek(T_dot, NULL)) {
         if (lex_accept(T_open_square)) {
+            /* if subscripted member's is not yet resolved, deference to resolve
```
Comment (jserv) [inline src/parser.c:1263]: There should be a comma (`,`) appearing right after "e.g.". That is, `e.g.,`.

See https://www.scribbr.com/definitions/for-example-abbreviation/

File: tests/driver.sh [hunk 6]
```diff
@@ -433,6 +433,49 @@ int main() {
...
+
+int main() {
+    strcpy(a, "DATA");
+    data_t *data = malloc(sizeof(data_t));
+    data->raw = a;
+    data_t data2;
+    data2.raw = a;
+    char *raw = data->raw;
+    char *raw2 = data2.raw;
+    // mixed arrow / dot with subscript operators dereference
```
Comment (DrXiao) [inline tests/driver.sh:456]: Although shecc supports `//`-style comments, I think it is better to write single-line comments in C89 style (`/* ... */`), even though this is just test code.

reference: [shecc/CONTRIBUTING.md](https://github.com/sysprog21/shecc/blob/master/CONTRIBUTING.md)

File: src/parser.c [hunk 7]
```diff
@@ -1260,6 +1260,22 @@ void read_lvalue(lvalue_t *lvalue,
     while (lex_peek(T_open_square, NULL) || lex_peek(T_arrow, NULL) ||
            lex_peek(T_dot, NULL)) {
         if (lex_accept(T_open_square)) {
+            /* if subscripted member's is not yet resolved, dereference to
```
Comment (DrXiao) [inline src/parser.c:1263]: How about separating the example from the explanation of the implementation?

That is, rewrite it as follows:
```c
/* If subscripted member's ....
 * ... base address.
 *
 * e.g., dereference of "->" ...
 * would be performed here.
 */
```

**Review by DrXiao — CHANGES_REQUESTED** [review]
I notice that the title of this pull request still uses "deference" in the wording. Fixing it to "dereference" is better and prevents misunderstandings.

Additionally, the git commit title is `Fix incorrect deref behavior`, and I believe it could be improved with a clearer summary.

File: src/parser.c [hunk 8]
```diff
@@ -1260,6 +1260,23 @@ void read_lvalue(lvalue_t *lvalue,
...
+             * resolve base addres.
```
Comment (DrXiao) [inline src/parser.c:1264]: typo: addres

**Review by DrXiao — COMMENTED** [review]
Except for the typo in the comment that needs to be fixed, please adjust the git commit message.

After fixing the typo and refining the git commit message, I think the proposed changes look good.

**Review by jserv — CHANGES_REQUESTED** [review]
Append the `Close #?` where `?` stands for the issue you are managing to close at the end of git commit messages.

**Comment by jserv** [comment]
Thank @ChAoSUnItY for contributing!
